require_relative '../lib/template_pattern/hero'
require_relative '../lib/template_pattern/warrior'
require_relative '../lib/template_pattern/mage'
require_relative '../lib/strategy_pattern/hero'
require_relative '../lib/strategy_pattern/battle_stats'
require_relative '../lib/strategy_pattern/skills_stats'
require_relative '../lib/observer_pattern/hero'
require_relative '../lib/observer_pattern/tile'
require_relative '../lib/iterator_pattern/inventory'
require_relative '../lib/iterator_pattern/item'
require_relative '../lib/iterator_pattern/inventory_iterator'
require_relative '../lib/command_pattern/amplify_shield_command'
require_relative '../lib/command_pattern/calibrate_driver_command'
require_relative '../lib/command_pattern/test_complier_command'
require_relative '../lib/command_pattern/install_regulator_command'
require_relative '../lib/command_pattern/robot'
require_relative '../lib/command_pattern/reactor'
require_relative '../lib/factory_pattern/party'
require_relative '../lib/singleton_pattern/hero_factory'
require_relative '../lib/builder_pattern/board'
require_relative '../lib/builder_pattern/tile_factory'
require_relative '../lib/builder_pattern/monster_factory'
require_relative '../lib/builder_pattern/board_builder'
require_relative '../lib/composite_pattern/encounter'
require_relative '../lib/composite_pattern/puzzle'
require_relative '../lib/composite_pattern/diplomacy'
require_relative '../lib/composite_pattern/composite_quest'
require_relative '../lib/composite_pattern/quest'
require_relative '../lib/composite_pattern/mega_quest'
require_relative '../lib/decorator_pattern/item'
require_relative '../lib/decorator_pattern/magic_decorator'
require_relative '../lib/decorator_pattern/masterpiece_decorator'
require_relative '../lib/proxy_pattern/robot_proxy'

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  config.order = 'random'
end
